### PR TITLE
Make fromPresent=true return all assignment with due date >= today

### LINKED ISSUE #19: [BUG]: fromPresent dueDate must focus on date.
## Describe the bug
The fromPresent should return the assignment that have dueDate >= today (Focus manly on Day not date-time)

## Expected behavior

Ex:
Current time - 12 Sep. 12:00
Assignment 1 Due date - 12 Sep. 11:00
Assignment 2 Due date - 13 Sep. 8:00

The assignment that should be returned to the user is both of them (Assignment 1 is included because it is still on 12 Sep.)

### PR DESCRIPTION
**Pull request by abounk**
fix #19

## PR Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others. (Please describe)

### Changes

1. Add test cases for this feature

### Fixes

1. fromPresent=true now returns all assignments with due date >= today.

### CODE REVIEW

**Review by sirateek — COMMENTED** [review]
This file is the test for the view `garnbarn_api/tests/test_frompresent.py`. So the test in this file should be in the test_view.py

**Review by sirateek — COMMENTED** [review]
I don't see the test for this case

Ex:
Current time - 12 Sep. 12:00
Assignment 1 Due date - 12 Sep. 11:00
Assignment 2 Due date - 13 Sep. 8:00

The assignment that should be returned to the user is both of them (Assignment 1 is included because it is still on 12 Sep.)

Did you test for it yet?

**Comment by abounk** [comment]
> file should be in the

I think ```garnbarn_api/tests/test_view.py``` contain too much of test cases, so I'm planning to separate them out.
Or do you think it's better to put the ```garnbarn_api/tests/test_frompresent.py``` in test_view.py?

**Comment by abounk** [comment]
> I don't see the test for this case
> 
> Ex: Current time - 12 Sep. 12:00 Assignment 1 Due date - 12 Sep. 11:00 Assignment 2 Due date - 13 Sep. 8:00
> 
> The assignment that should be returned to the user is both of them (Assignment 1 is included because it is still on 12 Sep.)
> 
> Did you test for it yet?

@sirateek 
I did. The way I test that is to create assignment object with specified due date (today, yesterday, tomorrow). Then in ```test_frompresent_is_true``` it will check if the response only contain 2 assignment obj. which is the one with due date = today and another one with due date = tomorrow. Or there is a better ways to test this just let me know.

**Comment by abounk** [comment]
> I don't see the test for this case
> 
> Ex: Current time - 12 Sep. 12:00 Assignment 1 Due date - 12 Sep. 11:00 Assignment 2 Due date - 13 Sep. 8:00
> 
> The assignment that should be returned to the user is both of them (Assignment 1 is included because it is still on 12 Sep.)
> 
> Did you test for it yet?

@sirateek 
Updated.

**Review by sirateek — APPROVED** [review]
LGTM

**Pull request merged**
